### PR TITLE
Adding Integration Tests

### PR DESCRIPTION
**Pull request by gauntface**
cc @Minishlink @marco-c 

This adds a set of tests that will open Chrome & Firefox stable, beta and unstable and check the push notifications are sending correctly.

Only thing it really needs is the ability to retry tests a few times (Largely because selenium tests are flakey on CI).

### CODE REVIEW

**Comment by Minishlink** [comment]
Thanks!

This works on Linux only right? On Ubuntu, it's stuck on "starting service". :/
Also, have you a Travis configuration that works with this?

**Comment by gauntface** [comment]
I haven't tried travis yet. Will take another look.

It should work on OS X unless the killing prices fails. The start takes
some time because it downloads chrome and Firefox (all three versions).

**Comment by Minishlink** [comment]
I was asking for Windows :) But Linux is fine.
So after some time, it finally exited with `Unable to find a service with ID 'phpunit'`, although `phpunit`is installed and can be invoked with the command `phpunit`.

**Comment by gauntface** [comment]
I'm just putting together a PR with Unit tests and added some additional error checking and logs so I'm *hoping* this will either reveal the issue OR better yet fix the issue.

The "testing service" in this case is given a name, in this phpunit, so what is says it can't find a service with ID "phpunit" it means it was expecting a background process ("the service") to be running with name "phpunit" but it couldn't find it.

I'll ping this PR and cc once I'm a little more confident this is working.

**Comment by gauntface** [comment]
Gonna close this PR.

While figuring out a number of issues with the testing service, looks like express + CURL for some reason aren't getting along so will re-open once I've fixed it.

**Pull request closed without merging**
